package application;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class DsController {//注册登录页面
	@FXML
    private Button showBtn;
	@FXML
	private TextField setName;
	@FXML
	private TextField setPass;

	@FXML
	private Label warnLabel;

	static int i = 0;

	private Stage stage;

	public void init(DsController controller, Stage stage){
		this.stage = stage;
	}

	@FXML
	private void signin(ActionEvent event) throws IOException {

		Teacher tea = new Teacher(setName.getText(), setPass.getText());//使用自定义的类暂时储存数据

      File Fl = new File("TeacherNum.txt");
      try (Scanner input = new Scanner(Fl)) {
           i = input.nextInt();
       }
      catch(Exception e){
          i = 0;
      }

       try (FileWriter out = new FileWriter("Teacher.txt",true)) {
           out.write("\t");
           out.write(tea.GetName() + "\t");

           out.write(tea.GetPass() + "\n");
       }

       i++;
       try(PrintWriter output = new PrintWriter(Fl)){
               output.print(i);
           }
		// TODO Autogenerated
       warnLabel.setText("注册成功");
	}

	@FXML
	private void onShowCon()throws FileNotFoundException{
		File Fl = new File("TeacherNum.txt");
        File fl = new File("Teacher.txt");
        try (Scanner input = new Scanner(Fl)) {
            i = input.nextInt();
        }

        String Password = setPass.getText();
        String Username = setName.getText();
        Teacher[] tea = new Teacher[i];
        int j;
        try(Scanner Input = new Scanner(fl)){
            for(j =0; j < i;j++){
                tea[j] = new Teacher(Input.next(), Input.next()
                        );
                if(Username.compareTo(tea[j].GetName()) == 0){
                	if(Password.compareTo(tea[j].GetPass()) == 0){
                		signup();
                	}else {
                		warnLabel.setText("密码错误");
                	}
                	break;
                }
            }
            if(j==i){
            	warnLabel.setText("未注册账户");
            }
        }
	}

    private void signup() {
    	try {
    		FXMLLoader loader = new FXMLLoader(getClass().getResource("/Menu.fxml"));
    		Parent conRoot = loader.load();
			Stage conStage = new Stage();

			MenuController converController =  loader.getController();
			converController.init(this, conStage);



			conStage.setTitle("主菜单");
			conStage.setScene(new Scene(conRoot));
			conRoot.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			conStage.show();

		} catch(Exception e) {
			e.printStackTrace();
		}
    }
}
